# site settings

title: necrux
description: necrux.com - A Tech Blog by Wes Henderson
taglong: Print until it makes sense!
tagshort: "- Blog"
url: https://necrux.com
baseurl: ""
permalink: pretty
repo: https://github.com/necrux/necrux.com

# author settings

author:
  name: Wes Henderson
  email: info@necrux.com
photo: /assets/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
